# Generated by Django 3.2.4 on 2021-06-22 17:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_rename_user_polluser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polluser',
            new_name='Profile',
        ),
    ]
