# Generated by Django 3.2.4 on 2021-06-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_profile_has_voted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='has_voted',
            new_name='question_1',
        ),
        migrations.AddField(
            model_name='profile',
            name='question_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='question_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='question_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='question_5',
            field=models.BooleanField(default=False),
        ),
    ]
